services:
  database:
    container_name: db
    restart: unless-stopped
    image: postgres:16.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_NAME: '${DB_USERNAME}'
      TZ: Asia/Seoul
    volumes:
      - ./.docker:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
  application:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: '${SPRING_PROFILES_ACTIVE}'
      DB_HOSTNAME: '${DB_HOSTNAME}'
      DB_PORT: '${DB_PORT}'
      DB_USERNAME: '${DB_USERNAME}'
      DB_PASSWORD: '${DB_PASSWORD}'
    depends_on:
      - database

volumes:
  pgdata:
    external: true